Capstone-project
Ambrosegithub/Capstone-project1 pull request #1
Opened 2022-07-01 20:47 UTC by Ambrosegithub

- [ ] add  2 index file for both home and about page.
- [ ] add 2 css file for both pages.
- [ ] add javascript file.
- [ ] create speaker section dynamically with Javascript.
- [ ] add Readme file for project description.
- [ ] add images.
- [ ] use HTML CSS AND JAVASCRIPT FOR THE PROJECT.
- [ ] use linter and git hub flow.

2022-07-01 21:55 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @Ambrosegithub,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] Some linters checks are not passed. So please fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-07-02 03:49 UTC, Ismailco commented
@Ambrosegithub, kindly fix your linter errors so you can get a review ASAP

2022-07-02 04:19 UTC, Kingstalux commented
Hi @Ambrosegithub , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] You have submitted a project, that has failing linters checks. Kindly fix those before submitting for a review 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-02 13:01 UTC, arslanbisharat requested changes
Hi @Ambrosegithub, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- There is no linter error is present. ✔️
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 13:01 UTC, arslanbisharat commented on README.md
> +# HTML & CSS3 & JavaScript Course
- [ ] Thank you so much for adding this readme file but this is not requested by Microverse. Please add a proper readme. You can check the [templates](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

2022-07-02 13:01 UTC, arslanbisharat commented on README.md
> +If you are not familiar with linters, read [root level README](../README.md).
- [ ] The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2022-07-02 13:01 UTC, arslanbisharat commented on README.md
> +   ```
- [ ] Please add a link to the live version of your project so it is easily accessible for anyone

2022-07-02 13:01 UTC, arslanbisharat commented on README.md
> +
- [ ] Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include

-     A description of the project.
-     A demo of the project features (different pages and different screen sizes).
-     You should also highlight some interesting piece of code or something you built that you are very proud of.
-

2022-07-02 13:01 UTC, arslanbisharat commented on index.html
> +    ></script>
- [ ] The bottom header is not fixed and doesn't reflect the design when scrolling up or down. 
![image](https://user-images.githubusercontent.com/58504655/177001485-79294892-eea5-4734-b913-f05a13c6fa0a.png)

2022-07-02 13:01 UTC, arslanbisharat commented on index.html
> +    <footer>
- [ ] On the desktop the partner section and footer doesn't match with the given design. Please make sure you follow the design. 

![image](https://user-images.githubusercontent.com/58504655/177001573-a0d8da25-d615-46fd-b690-432b3b2ea12b.png)

2022-07-02 13:01 UTC, arslanbisharat commented on index.html
> +      <section class="home-cont">
- [ ] Please make sure you follow the given layout and color scheme. 
![image](https://user-images.githubusercontent.com/58504655/177001623-9ad69a45-8f13-4d16-8c0a-deda12481cb6.png)

2022-07-02 13:01 UTC, arslanbisharat commented on About.html
> +                        <a id="about" href="./index.html" class="link">About</a>
- [ ] This is index page link so please remove About from here and add Home here,

2022-07-02 13:01 UTC, arslanbisharat commented on About.html
> +        </P>
- [ ] On mobile screen the menu button color and layout should match the given in the design. 
![image](https://user-images.githubusercontent.com/58504655/177001753-66258a7b-5f4c-46fa-841a-bff4e436e5fe.png)

2022-07-02 13:01 UTC, arslanbisharat commented on About.html
> +        </div>
- [ ] On mobile screen there are multiple issues present. For example, the text is not aligned. 

![image](https://user-images.githubusercontent.com/58504655/177001842-38b20ac9-1cdb-4bac-a5fd-e8962993dc3c.png)

2022-07-02 17:46 UTC, Ambrosegithub commented on About.html
> +        </P>
DONE

2022-07-02 17:47 UTC, Ambrosegithub commented
DONE

2022-07-02 17:47 UTC, Ambrosegithub commented
DONE

2022-07-02 17:47 UTC, Ambrosegithub commented on About.html
> +        </P>
DONE

2022-07-02 17:47 UTC, Ambrosegithub commented on About.html
> +                        <a id="about" href="./index.html" class="link">About</a>
DONE

2022-07-02 17:48 UTC, Ambrosegithub commented on About.html
> +                        <a id="about" href="./index.html" class="link">About</a>
DONE

2022-07-02 17:55 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @Ambrosegithub     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional Suggestion

- [ ] [OPTIONAL] Please add the image on top left of the speakers images as in the design

![image](https://user-images.githubusercontent.com/75126481/177011404-f3b2c7c1-8593-47d4-b5f2-6583c79128bc.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 18:01 UTC, merged